Added more icons
glints-dev/glints-aries pull request #904
Opened 2023-07-24 04:24 UTC by tonyling94

Added more icons to support employer and candidate chat interface.

2023-07-24 04:46 UTC, ninariccimarie requested changes
Hi @tonyling94 can you export the images from the group layer in Figma? you'll have to remove some sections on the svg file after as well. You can follow the instructions here: https://aries.glints.design/?path=/story/next-icon--page#adding-new-icons

2023-07-25 01:07 UTC, ninariccimarie commented on src/@next/Icon/icons/ri-attachment-fill.svg
> +<path d="M20.997 2.992L21 21.008C20.9979 21.2706 20.8926 21.5219 20.7068 21.7075C20.521 21.8931 20.2696 21.9982 20.007 22H3.993C3.72981 22 3.47739 21.8955 3.2912 21.7095C3.105 21.5235 3.00027 21.2712
I think you forgot to remove `fill="#626262"` part on all the svg. the indicator is they should be in black.

2023-07-25 01:25 UTC, tonyling94 commented on src/@next/Icon/icons/ri-attachment-fill.svg
> +<path d="M20.997 2.992L21 21.008C20.9979 21.2706 20.8926 21.5219 20.7068 21.7075C20.521 21.8931 20.2696 21.9982 20.007 22H3.993C3.72981 22 3.47739 21.8955 3.2912 21.7095C3.105 21.5235 3.00027 21.2712
opps, I'll push another fix. thanks!

2023-07-25 01:48 UTC, tonyling94 commented on src/@next/Icon/icons/ri-attachment-fill.svg
> +<path d="M20.997 2.992L21 21.008C20.9979 21.2706 20.8926 21.5219 20.7068 21.7075C20.521 21.8931 20.2696 21.9982 20.007 22H3.993C3.72981 22 3.47739 21.8955 3.2912 21.7095C3.105 21.5235 3.00027 21.2712
Fixed in 11488322b8202b62914b21238c37dbfbe89737f1

2023-07-25 05:37 UTC, ninariccimarie approved these changes
LGTM! thanks

2023-07-25 07:15 UTC, merged